export interface Country {
  code: string;
  name: string;
  namePt: string;
  flag: string;
  phoneCode: string;
  currency: string;
  currencySymbol: string;
  locale: string;
  dateFormat: string;
  timeFormat: "12h" | "24h";
  language: string;
  documentTypes: DocumentType[];
  minAge: number;
  hasCPF: boolean;
  hasCNPJ: boolean;
  hasRNE: boolean;
  hasPassport: boolean;
  states?: string[];
}

export interface DocumentType {
  id: string;
  name: string;
  namePt: string;
  regex: string;
  mask: string;
  length: number;
  acceptImage: boolean;
  acceptDigital: boolean;
}

export const COUNTRIES: Country[] = [
  {
    code: "BR",
    name: "Brazil",
    namePt: "Brasil",
    flag: "🇧🇷",
    phoneCode: "+55",
    currency: "BRL",
    currencySymbol: "R$",
    locale: "pt-BR",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "pt-BR",
    documentTypes: [
      { id: "cpf", name: "CPF", namePt: "CPF", regex: "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$", mask: "000.000.000-00", length: 11, acceptImage: true, acceptDigital: true },
      { id: "cnh", name: "CNH", namePt: "CNH", regex: "^\\d{11}$", mask: "00000000000", length: 11, acceptImage: true, acceptDigital: true },
      { id: "rg", name: "RG", namePt: "RG", regex: "^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-?[\\dxX]$", mask: "00.000.000-0", length: 9, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]{2}\\d{6}$", mask: "AA000000", length: 8, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: true,
    hasCNPJ: true,
    hasRNE: false,
    hasPassport: true,
    states: ["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"],
  },
  {
    code: "US",
    name: "United States",
    namePt: "Estados Unidos",
    flag: "🇺🇸",
    phoneCode: "+1",
    currency: "USD",
    currencySymbol: "$",
    locale: "en-US",
    dateFormat: "MM/DD/YYYY",
    timeFormat: "12h",
    language: "en-US",
    documentTypes: [
      { id: "ssn", name: "SSN", namePt: "SSN", regex: "^\\d{3}-\\d{2}-\\d{4}$", mask: "000-00-0000", length: 9, acceptImage: true, acceptDigital: false },
      { id: "drivers_license", name: "Driver's License", namePt: "Carteira de Motorista", regex: "^[A-Z0-9]{6,16}$", mask: "00000000", length: 8, acceptImage: true, acceptDigital: true },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^\\d{9}$", mask: "000000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 16,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
    states: ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"],
  },
  {
    code: "PT",
    name: "Portugal",
    namePt: "Portugal",
    flag: "🇵🇹",
    phoneCode: "+351",
    currency: "EUR",
    currencySymbol: "€",
    locale: "pt-PT",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "pt-PT",
    documentTypes: [
      { id: "cc", name: "Citizen Card", namePt: "Cartão de Cidadão", regex: "^\\d{8}$", mask: "00000000", length: 8, acceptImage: true, acceptDigital: true },
      { id: "nif", name: "NIF", namePt: "NIF", regex: "^\\d{9}$", mask: "000000000", length: 9, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]{2}\\d{6}$", mask: "AA000000", length: 8, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "AR",
    name: "Argentina",
    namePt: "Argentina",
    flag: "🇦🇷",
    phoneCode: "+54",
    currency: "ARS",
    currencySymbol: "$",
    locale: "es-AR",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "es-AR",
    documentTypes: [
      { id: "dni", name: "DNI", namePt: "DNI", regex: "^\\d{7,8}$", mask: "00000000", length: 8, acceptImage: true, acceptDigital: true },
      { id: "cuit", name: "CUIT", namePt: "CUIT", regex: "^\\d{2}-\\d{8}-\\d{1}$", mask: "00-00000000-0", length: 11, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]{3}\\d{6}$", mask: "AAA000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
    states: ["CABA","BA","CAT","CH","CB","CR","ER","FO","JU","LP","MZA","MIS","NE","RN","SA","SJ","SL","SF","SDE","TF","TUC"],
  },
  {
    code: "MX",
    name: "Mexico",
    namePt: "México",
    flag: "🇲🇽",
    phoneCode: "+52",
    currency: "MXN",
    currencySymbol: "$",
    locale: "es-MX",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "12h",
    language: "es-MX",
    documentTypes: [
      { id: "curp", name: "CURP", namePt: "CURP", regex: "^[A-Z]{4}\\d{6}[A-Z]{6}\\d{2}$", mask: "AAAA000000AAAAAA00", length: 18, acceptImage: true, acceptDigital: true },
      { id: "rfc", name: "RFC", namePt: "RFC", regex: "^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$", mask: "AAA000000AAA", length: 13, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^\\d{9}$", mask: "000000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "CO",
    name: "Colombia",
    namePt: "Colômbia",
    flag: "🇨🇴",
    phoneCode: "+57",
    currency: "COP",
    currencySymbol: "$",
    locale: "es-CO",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "es-CO",
    documentTypes: [
      { id: "cc", name: "Cédula Ciudadanía", namePt: "Cédula de Cidadania", regex: "^\\d{6,10}$", mask: "00000000", length: 10, acceptImage: true, acceptDigital: true },
      { id: "nit", name: "NIT", namePt: "NIT", regex: "^\\d{9}-\\d{1}$", mask: "000000000-0", length: 10, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]{2}\\d{7}$", mask: "AA0000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "CL",
    name: "Chile",
    namePt: "Chile",
    flag: "🇨🇱",
    phoneCode: "+56",
    currency: "CLP",
    currencySymbol: "$",
    locale: "es-CL",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "es-CL",
    documentTypes: [
      { id: "rut", name: "RUT", namePt: "RUT", regex: "^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-[\\dkK]$", mask: "00.000.000-0", length: 9, acceptImage: true, acceptDigital: true },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z0-9]{8,9}$", mask: "000000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "PE",
    name: "Peru",
    namePt: "Peru",
    flag: "🇵🇪",
    phoneCode: "+51",
    currency: "PEN",
    currencySymbol: "S/",
    locale: "es-PE",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "es-PE",
    documentTypes: [
      { id: "dni", name: "DNI", namePt: "DNI", regex: "^\\d{8}$", mask: "00000000", length: 8, acceptImage: true, acceptDigital: true },
      { id: "ruc", name: "RUC", namePt: "RUC", regex: "^\\d{11}$", mask: "00000000000", length: 11, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]{2}\\d{6}$", mask: "AA000000", length: 8, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "GB",
    name: "United Kingdom",
    namePt: "Reino Unido",
    flag: "🇬🇧",
    phoneCode: "+44",
    currency: "GBP",
    currencySymbol: "£",
    locale: "en-GB",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "12h",
    language: "en-GB",
    documentTypes: [
      { id: "ni", name: "National Insurance", namePt: "Seguro Nacional", regex: "^[A-CEGHJ-PR-TW-Z]{2}\\d{6}[A-D]?$", mask: "AA000000A", length: 9, acceptImage: true, acceptDigital: false },
      { id: "drivers_license", name: "Driver's License", namePt: "Carteira de Motorista", regex: "^[A-Z0-9]{16}$", mask: "AAAA000000AAAAAA", length: 16, acceptImage: true, acceptDigital: true },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^\\d{9}$", mask: "000000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 17,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "ES",
    name: "Spain",
    namePt: "Espanha",
    flag: "🇪🇸",
    phoneCode: "+34",
    currency: "EUR",
    currencySymbol: "€",
    locale: "es-ES",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "es-ES",
    documentTypes: [
      { id: "dni", name: "DNI", namePt: "DNI", regex: "^\\d{8}[A-Z]$", mask: "00000000A", length: 9, acceptImage: true, acceptDigital: true },
      { id: "nie", name: "NIE", namePt: "NIE", regex: "^[XYZ]\\d{7}[A-Z]$", mask: "X0000000A", length: 9, acceptImage: true, acceptDigital: true },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]{3}\\d{6}$", mask: "AAA000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "FR",
    name: "France",
    namePt: "França",
    flag: "🇫🇷",
    phoneCode: "+33",
    currency: "EUR",
    currencySymbol: "€",
    locale: "fr-FR",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "fr-FR",
    documentTypes: [
      { id: "insee", name: "INSEE", namePt: "INSEE", regex: "^\\d{15}$", mask: "000000000000000", length: 15, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^\\d{9}[A-Z]{2}\\d{3}$", mask: "000000000AA000", length: 14, acceptImage: true, acceptDigital: true },
      { id: "drivers_license", name: "Permis de Conduire", namePt: "Carteira de Motorista", regex: "^\\d{12}$", mask: "000000000000", length: 12, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "DE",
    name: "Germany",
    namePt: "Alemanha",
    flag: "🇩🇪",
    phoneCode: "+49",
    currency: "EUR",
    currencySymbol: "€",
    locale: "de-DE",
    dateFormat: "DD.MM.YYYY",
    timeFormat: "24h",
    language: "de-DE",
    documentTypes: [
      { id: "personalausweis", name: "Personalausweis", namePt: "Documento de Identidade", regex: "^[A-Z0-9]{9}$", mask: "AAAA00000", length: 9, acceptImage: true, acceptDigital: true },
      { id: "steuerid", name: "Steuer-ID", namePt: "ID Fiscal", regex: "^\\d{11}$", mask: "00000000000", length: 11, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z0-9]{9}$", mask: "AAAA00000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "IT",
    name: "Italy",
    namePt: "Itália",
    flag: "🇮🇹",
    phoneCode: "+39",
    currency: "EUR",
    currencySymbol: "€",
    locale: "it-IT",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "it-IT",
    documentTypes: [
      { id: "codice_fiscale", name: "Codice Fiscale", namePt: "Código Fiscal", regex: "^[A-Z]{6}\\d{2}[A-Z]\\d{2}[A-Z]\\d{3}[A-Z]$", mask: "AAAAAA00A00A000A", length: 16, acceptImage: true, acceptDigital: true },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z0-9]{9}$", mask: "AAAA00000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "JP",
    name: "Japan",
    namePt: "Japão",
    flag: "🇯🇵",
    phoneCode: "+81",
    currency: "JPY",
    currencySymbol: "¥",
    locale: "ja-JP",
    dateFormat: "YYYY/MM/DD",
    timeFormat: "24h",
    language: "ja-JP",
    documentTypes: [
      { id: "my_number", name: "My Number", namePt: "Meu Número", regex: "^\\d{12}$", mask: "000000000000", length: 12, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]{2}\\d{7}$", mask: "AA0000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "CN",
    name: "China",
    namePt: "China",
    flag: "🇨🇳",
    phoneCode: "+86",
    currency: "CNY",
    currencySymbol: "¥",
    locale: "zh-CN",
    dateFormat: "YYYY-MM-DD",
    timeFormat: "24h",
    language: "zh-CN",
    documentTypes: [
      { id: "id_card", name: "ID Card", namePt: "Cartão de Identidade", regex: "^\\d{18}[\\dX]$", mask: "000000000000000000", length: 18, acceptImage: true, acceptDigital: true },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]\\d{8}$", mask: "A00000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
    states: ["BJ","SH","GD","ZJ","JS","SC","SD","HN","HB","FJ","AH","LN","CQ","SX","HLJ","HL","JX","YN","GZ","SN","GS","NX","QH","XJ","XZ","NM","GX","TW","HK","MO"],
  },
  {
    code: "IN",
    name: "India",
    namePt: "Índia",
    flag: "🇮🇳",
    phoneCode: "+91",
    currency: "INR",
    currencySymbol: "₹",
    locale: "hi-IN",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "12h",
    language: "hi-IN",
    documentTypes: [
      { id: "aadhaar", name: "Aadhaar", namePt: "Aadhaar", regex: "^\\d{12}$", mask: "000000000000", length: 12, acceptImage: true, acceptDigital: true },
      { id: "pan", name: "PAN", namePt: "PAN", regex: "^[A-Z]{5}\\d{4}[A-Z]$", mask: "AAAAA0000A", length: 10, acceptImage: true, acceptDigital: true },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]\\d{7}$", mask: "A0000000", length: 8, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
    states: ["AP","AR","AS","BR","CG","GA","GJ","HR","HP","JH","KA","KL","MP","MH","MN","ML","MZ","NL","OD","PB","RJ","SK","TN","TS","TR","UP","UK","WB"],
  },
  {
    code: "AO",
    name: "Angola",
    namePt: "Angola",
    flag: "🇦🇴",
    phoneCode: "+244",
    currency: "AOA",
    currencySymbol: "Kz",
    locale: "pt-AO",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "pt-AO",
    documentTypes: [
      { id: "bi", name: "BI", namePt: "Bilhete de Identidade", regex: "^\\d{9}$", mask: "000000000", length: 9, acceptImage: true, acceptDigital: true },
      { id: "nif", name: "NIF", namePt: "NIF", regex: "^\\d{10}$", mask: "0000000000", length: 10, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]{2}\\d{6}$", mask: "AA000000", length: 8, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "MZ",
    name: "Mozambique",
    namePt: "Moçambique",
    flag: "🇲🇿",
    phoneCode: "+258",
    currency: "MZN",
    currencySymbol: "MT",
    locale: "pt-MZ",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "pt-MZ",
    documentTypes: [
      { id: "bi", name: "BI", namePt: "Bilhete de Identidade", regex: "^\\d{9}[A-Z]?$", mask: "000000000", length: 9, acceptImage: true, acceptDigital: true },
      { id: "nuit", name: "NUIT", namePt: "NUIT", regex: "^\\d{9}$", mask: "000000000", length: 9, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]{2}\\d{6}$", mask: "AA000000", length: 8, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
  },
  {
    code: "NG",
    name: "Nigeria",
    namePt: "Nigéria",
    flag: "🇳🇬",
    phoneCode: "+234",
    currency: "NGN",
    currencySymbol: "₦",
    locale: "en-NG",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "12h",
    language: "en-NG",
    documentTypes: [
      { id: "nin", name: "NIN", namePt: "NIN", regex: "^\\d{11}$", mask: "00000000000", length: 11, acceptImage: true, acceptDigital: true },
      { id: "bvn", name: "BVN", namePt: "BVN", regex: "^\\d{10}$", mask: "0000000000", length: 10, acceptImage: true, acceptDigital: false },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z]\\d{8}$", mask: "A00000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
    states: ["AB","AD","AK","AN","BA","BE","BO","BY","CR","DE","EB","ED","EK","EN","FC","GO","IM","JI","KD","KE","KN","KO","KT","KW","LA","NA","NI","OG","ON","OS","OY","PL","RI","SO","TA","YO","ZA"],
  },
  {
    code: "ZA",
    name: "South Africa",
    namePt: "África do Sul",
    flag: "🇿🇦",
    phoneCode: "+27",
    currency: "ZAR",
    currencySymbol: "R",
    locale: "en-ZA",
    dateFormat: "YYYY/MM/DD",
    timeFormat: "24h",
    language: "en-ZA",
    documentTypes: [
      { id: "id_number", name: "ID Number", namePt: "Número de ID", regex: "^\\d{13}$", mask: "0000000000000", length: 13, acceptImage: true, acceptDigital: true },
      { id: "passport", name: "Passport", namePt: "Passaporte", regex: "^[A-Z0-9]{8,9}$", mask: "000000000", length: 9, acceptImage: true, acceptDigital: true },
    ],
    minAge: 18,
    hasCPF: false,
    hasCNPJ: false,
    hasRNE: false,
    hasPassport: true,
    states: ["EC","FS","GP","KZN","LP","MP","NC","NW","WC"],
  },
];

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code);
}

export function getDocumentType(countryCode: string, docId: string): DocumentType | undefined {
  const country = getCountryByCode(countryCode);
  return country?.documentTypes.find(d => d.id === docId);
}
