import { NextResponse } from "next/server"

export async function GET() {
  const sql = [
    "-- ============================================================",
    "-- TXAP MIGRACOES #4 + #5",
    "-- Company Subscriptions + Seguranca + 4 Contas + Favoritos + Admin",
    "-- ============================================================",
    "",
    "-- MIGRATION #4: COMPANY SUBSCRIPTIONS",
    "",
    "CREATE TABLE IF NOT EXISTS public.company_subscription_plans (",
    "    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,",
    "    name TEXT NOT NULL,",
    "    price_weekly DECIMAL(10,2) NOT NULL,",
    "    description TEXT,",
    "    features JSONB DEFAULT '[]'::jsonb,",
    "    max_products INTEGER DEFAULT 0,",
    "    is_featured BOOLEAN DEFAULT FALSE,",
    "    priority_score INTEGER DEFAULT 0,",
    "    is_active BOOLEAN DEFAULT TRUE,",
    "    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL",
    ");",
    "",
    "CREATE TABLE IF NOT EXISTS public.company_subscriptions (",
    "    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,",
    "    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,",
    "    plan_id UUID REFERENCES public.company_subscription_plans(id) ON DELETE SET NULL,",
    "    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'cancelled', 'expired', 'trial')),",
    "    auto_renew BOOLEAN DEFAULT TRUE,",
    "    current_period_start TIMESTAMP WITH TIME ZONE NOT NULL,",
    "    current_period_end TIMESTAMP WITH TIME ZONE NOT NULL,",
    "    stripe_subscription_id TEXT,",
    "    stripe_payment_method_id TEXT,",
    "    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,",
    "    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,",
    "    UNIQUE (company_id)",
    ");",
    "",
    "ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS has_own_delivery BOOLEAN DEFAULT FALSE;",
    "ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS needs_delivery_partner BOOLEAN DEFAULT FALSE;",
    "ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS delivery_zone_radius_km DECIMAL(10,2) DEFAULT 5;",
    "ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS service_categories TEXT[] DEFAULT '{}';",
    "ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;",
    "ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS priority_score INTEGER DEFAULT 0;",
    "",
    "CREATE TABLE IF NOT EXISTS public.company_delivery_partners (",
    "    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,",
    "    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,",
    "    driver_id UUID REFERENCES public.driver_profiles(id) ON DELETE CASCADE NOT NULL,",
    "    commission_percent DECIMAL(5,2) DEFAULT 15.00,",
    "    is_active BOOLEAN DEFAULT TRUE,",
    "    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,",
    "    UNIQUE (company_id, driver_id)",
    ");",
    "",
    "CREATE TABLE IF NOT EXISTS public.company_invoices (",
    "    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,",
    "    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,",
    "    subscription_id UUID REFERENCES public.company_subscriptions(id) ON DELETE SET NULL,",
    "    amount DECIMAL(10,2) NOT NULL,",
    "    period_start TIMESTAMP WITH TIME ZONE NOT NULL,",
    "    period_end TIMESTAMP WITH TIME ZONE NOT NULL,",
    "    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'overdue', 'cancelled')),",
    "    stripe_invoice_id TEXT,",
    "    payment_intent_id TEXT,",
    "    paid_at TIMESTAMP WITH TIME ZONE,",
    "    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL",
    ");",
    "",
    "ALTER TABLE public.company_subscription_plans ENABLE ROW LEVEL SECURITY;",
    "ALTER TABLE public.company_subscriptions ENABLE ROW LEVEL SECURITY;",
    "ALTER TABLE public.company_delivery_partners ENABLE ROW LEVEL SECURITY;",
    "ALTER TABLE public.company_invoices ENABLE ROW LEVEL SECURITY;",
    "",
    "DO $$ BEGIN CREATE POLICY public_read_plans ON public.company_subscription_plans FOR SELECT USING (true); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "DO $$ BEGIN CREATE POLICY company_own_sub ON public.company_subscriptions FOR ALL USING (auth.uid() = company_id); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "DO $$ BEGIN CREATE POLICY company_view_partners ON public.company_delivery_partners FOR SELECT USING (auth.uid() = company_id); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "DO $$ BEGIN CREATE POLICY driver_view_partners ON public.company_delivery_partners FOR SELECT USING (auth.uid() = driver_id); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "DO $$ BEGIN CREATE POLICY company_view_invoices ON public.company_invoices FOR SELECT USING (auth.uid() = company_id); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "",
    "CREATE INDEX IF NOT EXISTS idx_company_subscriptions_company ON public.company_subscriptions (company_id);",
    "CREATE INDEX IF NOT EXISTS idx_company_subscriptions_status ON public.company_subscriptions (status);",
    "CREATE INDEX IF NOT EXISTS idx_company_invoices_company ON public.company_invoices (company_id, created_at DESC);",
    "CREATE INDEX IF NOT EXISTS idx_company_invoices_status ON public.company_invoices (status);",
    "CREATE INDEX IF NOT EXISTS idx_companies_featured ON public.companies (is_featured, priority_score DESC) WHERE is_featured = TRUE;",
    "",
    "INSERT INTO public.company_subscription_plans (name, price_weekly, description, features, max_products, is_featured, priority_score) VALUES",
    "('Gratis', 0, 'Listagem basica no diretorio', '[\"Aparece na busca\", \"1 foto\"]', 3, FALSE, 0),",
    "('Destaque', 300, 'Aparece primeiro para todos os usuarios', '[\"Aparece no topo da busca\", \"Badge Destaque\", \"Ate 20 produtos\", \"Relatorio semanal\", \"Suporte prioritario\"]', 20, TRUE, 50),",
    "('Premium', 500, 'Tudo do Destaque + entrega TXAP integrada', '[\"Tudo do Destaque\", \"Entrega integrada com motoboys TXAP\", \"Sem taxa por entrega\", \"Gestao de pedidos\", \"Ate 50 produtos\", \"Relatorio completo\"]', 50, TRUE, 100)",
    "ON CONFLICT DO NOTHING;",
    "",
    "-- ============================================================",
    "-- MIGRATION #5: SEGURANCA, 4 TIPOS, FAVORITOS, ADMIN",
    "-- ============================================================",
    "",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone VARCHAR(20) UNIQUE;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT false;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS cpf VARCHAR(14) UNIQUE;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS cpf_verified BOOLEAN DEFAULT false;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS account_type VARCHAR(20) DEFAULT 'passenger' CHECK (account_type IN ('passenger', 'driver_moto', 'driver_car', 'business'));",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_banned BOOLEAN DEFAULT false;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS ban_reason TEXT;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS banned_at TIMESTAMPTZ;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS banned_by UUID REFERENCES profiles(id);",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS device_fingerprint TEXT;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS can_change_name BOOLEAN DEFAULT true;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS name_last_changed_at TIMESTAMPTZ;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS signup_attempts INTEGER DEFAULT 0;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_signup_attempt_at TIMESTAMPTZ;",
    "",
    "CREATE INDEX IF NOT EXISTS idx_profiles_phone ON profiles(phone);",
    "CREATE INDEX IF NOT EXISTS idx_profiles_cpf ON profiles(cpf);",
    "CREATE INDEX IF NOT EXISTS idx_profiles_banned ON profiles(is_banned) WHERE is_banned = true;",
    "CREATE INDEX IF NOT EXISTS idx_profiles_device ON profiles(device_fingerprint);",
    "CREATE INDEX IF NOT EXISTS idx_profiles_type ON profiles(account_type);",
    "CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);",
    "",
    "CREATE TABLE IF NOT EXISTS banned_devices (",
    "  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),",
    "  device_fingerprint TEXT NOT NULL UNIQUE,",
    "  reason TEXT,",
    "  banned_at TIMESTAMPTZ DEFAULT NOW(),",
    "  banned_by UUID REFERENCES profiles(id)",
    ");",
    "ALTER TABLE banned_devices ENABLE ROW LEVEL SECURITY;",
    "DO $$ BEGIN CREATE POLICY admin_full_banned_devices ON banned_devices FOR ALL USING (auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "",
    "CREATE TABLE IF NOT EXISTS signup_attempts_log (",
    "  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),",
    "  ip_address TEXT,",
    "  phone VARCHAR(20),",
    "  cpf VARCHAR(14),",
    "  device_fingerprint TEXT,",
    "  attempted_at TIMESTAMPTZ DEFAULT NOW(),",
    "  success BOOLEAN DEFAULT false",
    ");",
    "ALTER TABLE signup_attempts_log ENABLE ROW LEVEL SECURITY;",
    "DO $$ BEGIN CREATE POLICY admin_full_signup_log ON signup_attempts_log FOR ALL USING (auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "CREATE INDEX IF NOT EXISTS idx_signup_ip ON signup_attempts_log(ip_address, attempted_at);",
    "CREATE INDEX IF NOT EXISTS idx_signup_phone ON signup_attempts_log(phone, attempted_at);",
    "",
    "CREATE TABLE IF NOT EXISTS influencers (",
    "  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),",
    "  instagram_handle VARCHAR(100) NOT NULL,",
    "  display_name VARCHAR(255) NOT NULL,",
    "  avatar_url TEXT,",
    "  bio TEXT,",
    "  is_founder BOOLEAN DEFAULT false,",
    "  is_active BOOLEAN DEFAULT true,",
    "  display_order INTEGER DEFAULT 0,",
    "  click_count INTEGER DEFAULT 0,",
    "  created_by UUID REFERENCES profiles(id),",
    "  created_at TIMESTAMPTZ DEFAULT NOW()",
    ");",
    "ALTER TABLE influencers ENABLE ROW LEVEL SECURITY;",
    "DO $$ BEGIN CREATE POLICY public_read_influencers ON influencers FOR SELECT USING (true); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "DO $$ BEGIN CREATE POLICY admin_full_influencers ON influencers FOR ALL USING (auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "",
    "CREATE TABLE IF NOT EXISTS favorites (",
    "  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),",
    "  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,",
    "  favorite_type VARCHAR(20) NOT NULL CHECK (favorite_type IN ('driver', 'place', 'route')),",
    "  driver_id UUID REFERENCES profiles(id),",
    "  place_name VARCHAR(255),",
    "  place_address TEXT,",
    "  place_lat NUMERIC(10,8),",
    "  place_lng NUMERIC(11,8),",
    "  place_icon VARCHAR(10),",
    "  route_from_lat NUMERIC(10,8),",
    "  route_from_lng NUMERIC(11,8),",
    "  route_to_lat NUMERIC(10,8),",
    "  route_to_lng NUMERIC(11,8),",
    "  route_from_name VARCHAR(255),",
    "  route_to_name VARCHAR(255),",
    "  route_vehicle_type VARCHAR(20),",
    "  created_at TIMESTAMPTZ DEFAULT NOW()",
    ");",
    "ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;",
    "DO $$ BEGIN CREATE POLICY user_own_favorites ON favorites FOR ALL USING (auth.uid() = user_id); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "CREATE INDEX IF NOT EXISTS idx_favorites_user ON favorites(user_id);",
    "CREATE INDEX IF NOT EXISTS idx_favorites_type ON favorites(favorite_type);",
    "",
    "CREATE TABLE IF NOT EXISTS global_config (",
    "  key TEXT PRIMARY KEY,",
    "  value TEXT NOT NULL,",
    "  description TEXT,",
    "  updated_at TIMESTAMPTZ DEFAULT NOW(),",
    "  updated_by UUID REFERENCES profiles(id)",
    ");",
    "ALTER TABLE global_config ENABLE ROW LEVEL SECURITY;",
    "DO $$ BEGIN CREATE POLICY admin_full_config ON global_config FOR ALL USING (auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')); EXCEPTION WHEN duplicate_object THEN null; END $$;",
    "",
    "INSERT INTO global_config (key, value, description) VALUES",
    "('platform_commission', '0.10', 'Comissao da plataforma (10%)'),",
    "('min_price_per_km_moto', '1.00', 'Preco minimo por km para moto'),",
    "('min_price_per_km_carro', '1.50', 'Preco minimo por km para carro'),",
    "('max_price_per_km', '20.00', 'Preco maximo por km'),",
    "('genesis_guarantee_amount', '500', 'Garantia Genesis em reais'),",
    "('genesis_guarantee_days', '30', 'Dias da garantia Genesis'),",
    "('social_fee_percent', '1.0', 'Porcentagem para fundo social TXAP')",
    "ON CONFLICT DO NOTHING;",
    "",
    "-- ============================================================",
    "-- POSTGIS + NEARBY DRIVERS (Mapa em tempo real)",
    "-- ============================================================",
    "",
    "CREATE EXTENSION IF NOT EXISTS postgis;",
    "",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS location_updated_at TIMESTAMPTZ;",
    "ALTER TABLE profiles ADD COLUMN IF NOT EXISTS location GEOGRAPHY(POINT,4326);",
    "",
    "CREATE INDEX IF NOT EXISTS idx_profiles_location ON profiles USING GIST(location);",
    "",
    "CREATE OR REPLACE FUNCTION nearby_drivers(",
    "  user_lat NUMERIC,",
    "  user_lng NUMERIC,",
    "  search_radius NUMERIC,",
    "  v_type TEXT DEFAULT NULL",
    ")",
    "RETURNS TABLE (",
    "  id UUID,",
    "  name TEXT,",
    "  lat NUMERIC,",
    "  lng NUMERIC,",
    "  vehicle_type TEXT,",
    "  rating NUMERIC,",
    "  price_per_km NUMERIC,",
    "  distance_meters NUMERIC,",
    "  is_online BOOLEAN",
    ") AS $$",
    "BEGIN",
    "  RETURN QUERY",
    "  SELECT",
    "    p.id,",
    "    p.full_name::TEXT as name,",
    "    ST_Y(p.location::geometry)::NUMERIC as lat,",
    "    ST_X(p.location::geometry)::NUMERIC as lng,",
    "    dp.vehicle_type::TEXT,",
    "    COALESCE(p.rating, 4.5)::NUMERIC as rating,",
    "    COALESCE(dp.price_per_km, 3.00)::NUMERIC as price_per_km,",
    "    ST_Distance(p.location, ST_SetSRID(ST_MakePoint(user_lng, user_lat), 4326)::geography)::NUMERIC as distance_meters,",
    "    COALESCE(p.is_online, false) as is_online",
    "  FROM profiles p",
    "  JOIN driver_profiles dp ON dp.id = p.id",
    "  WHERE",
    "    p.role = 'driver'",
    "    AND p.is_online = true",
    "    AND COALESCE(p.is_banned, false) = false",
    "    AND p.location IS NOT NULL",
    "    AND ST_DWithin(p.location, ST_SetSRID(ST_MakePoint(user_lng, user_lat), 4326)::geography, search_radius)",
    "    AND (v_type IS NULL OR dp.vehicle_type = v_type)",
    "  ORDER BY distance_meters ASC",
    "  LIMIT 20;",
    "END;",
    "$$ LANGUAGE plpgsql;",
  ].join("\n")

  return NextResponse.json({
    note: "Execute o SQL abaixo no Supabase SQL Editor.",
    instructions: [
      "1. Acesse https://supabase.com/dashboard/project/hqydwwfulatawjpottlf/sql/new",
      "2. Cole TODO o SQL que esta no campo 'sql' abaixo",
      "3. Execute (Ctrl+Enter)",
      "4. Depois recarregue o app em https://txap.vercel.app",
    ],
    sql,
  })
}
